# Generated by Django 5.1.1 on 2024-09-17 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_subtitle_file_video_subtitle_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embedded_file',
            field=models.FileField(blank=True, null=True, upload_to='embedded/'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='videos.video'),
        ),
    ]
