# Generated by Django 5.1.1 on 2024-09-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_subtitle_text_remove_subtitle_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='file',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='language',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='text',
            field=models.TextField(default='No subtitle text'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='timestamp',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
    ]
