# Generated by Django 5.1.1 on 2024-09-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_subtitle_file_remove_subtitle_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_files',
            field=models.JSONField(default=list),
        ),
    ]
