# Generated by Django 5.1.1 on 2024-09-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_subtitle_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='text',
        ),
        migrations.RemoveField(
            model_name='subtitle',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='video',
            name='subtitle_file',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='file',
            field=models.FileField(default='default_subtitle.srt', upload_to='subtitles/'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
