# Generated by Django 5.1.1 on 2024-09-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_subtitle_text_remove_subtitle_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
