# Generated by Django 5.1.1 on 2024-09-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_subtitle_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='file',
            field=models.FileField(upload_to='subtitles/'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
